server:
  port: 7001
  
db:
  dataSource:
    url: jdbc:oracle:thin:@fullhouse.c1d2wea4uxbf.ap-northeast-2.rds.amazonaws.com:1521:JAVA
    driver-class-name: oracle.jdbc.OracleDriver
    username: station4
    password: pjh871107
  hibernate:
    hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
#    hibernate.query.substitutions: true 'Y', false 'N'
    hibernate.format_sql: true
    hibernate.jdbc.batch_size: 0
#    hibernate.cache.provider_class: org.hibernate.cache.SingletonEhCacheProvider
#    hibernate.cache.use_second_level_cache: true
#    hibernate.cache.use_query_cache: true
#    hibernate.cache.region.factory_class: org.hibernate.cache.infinispan.JndiInfinispanRegionFactory
    hibernate.enable_lazy_load_no_trans: true
    hibernate.generate_statistics: true
    hibernate.jdbc.use_streams_for_binary: true
    hibernate.ejb.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    hibernate.connection.charSet: UTF-8
    hibernate.validator.apply_to_ddl: false
    hibernate.validator.autoregister_listeners: false
    
#    connection.driver.class: oracle.jdbc.OracleDriver
#    connection.url: jdbc:oracle:thin:@fullhouse.c1d2wea4uxbf.ap-northeast-2.rds.amazonaws.com:1521:JAVA
#    connection.username: station4
#    connection.password: pjh871107



logging:
  level:
    root: info
    com:
      prac:
        angular: debug

    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace
             
      
  
spring:
    datasource:
#      url: jdbc:oracle:thin:@fullhouse.c1d2wea4uxbf.ap-northeast-2.rds.amazonaws.com:1521:JAVA
      url: jdbc:oracle:thin:@plannist.cn97lepujcj7.ap-northeast-2.rds.amazonaws.com:1521:ORCL
      driver-class-name: oracle.jdbc.OracleDriver
#      username: station4
#      password: pjh871107
      username: plannist
      password: pjh871107
    jpa:
      show-sql: true
#    database: oracle
#    database-platform: org.hibernate.dialect.Oracle10gDialect
#    generate-ddl: false
    
      properties:
        hibernate:
          format_sql: true
          enable_lazy_load_no_trans: true
#    
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl 
    
#    mvc:
#    static-path-pattern: /resources/static/**    
 
  
---
 mybatis:
  mapper-locations: classpath:com/prac/angular/mapper/**/*.xml
  configuration:
    lazyLoadingEnabled: true
    aggressiveLazyLoading: false
    mapUnderscoreToCamelCase: true
    
  
